# Generated by Django 5.0.3 on 2024-03-25 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_customer_store_custo_last_na_2e448d_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='promotion',
            new_name='promotions',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='unit_price',
        ),
    ]
