# Generated by Django 5.0.3 on 2024-03-25 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_last_updated_product_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='-', null=True),
        ),
    ]
