# Generated by Django 5.0.3 on 2024-03-25 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_phone_number_customer_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='Order',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='unit_Price',
            new_name='unit_price',
        ),
    ]
